- name: Clean reproducer layout
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: true
  tasks:
    - name: Call reproducer.cleanup
      ansible.builtin.import_role:
        name: reproducer
        tasks_from: cleanup.yml
