---
- name: Install required packages
  tags:
    - packages
  become: true
  ansible.builtin.package:
    name:
      - python3-devel
      - python3-pip
      - podman
      - buildah
    state: latest

- name: Get tcib from repository
  ansible.builtin.git:
    accept_hostkey: true
    dest: "{{ cifmw_build_containers_basedir }}/tmp/tcib"
    repo: "{{ cifmw_build_containers_tcib_src }}"

  # FIXME(Chandan/arxcruz): Skip usage of sudo installation
- name: Install tcib package
  become: true
  ci_script:
    output_dir: "{{ cifmw_build_containers_basedir }}/artifacts"
    script: |
      pip install -r requirements.txt
      python setup.py install
    chdir: "{{ cifmw_build_containers_basedir }}/tmp/tcib"
